services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: prm
      POSTGRES_PASSWORD: prm
      POSTGRES_DB: prm
    ports:
      - "5433:5432"
    volumes:
      - prm_pgdata:/var/lib/postgresql/data

volumes:
  prm_pgdata:
