"""initial schema

Revision ID: 7f125d93f175
Revises: 
Create Date: 2026-06-08 10:10:38.713141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f125d93f175'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_predefined', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.String(length=20), nullable=False),
    sa.Column('llm_api_key', sa.String(length=500), nullable=False),
    sa.Column('scheduler_interval_hours', sa.Integer(), nullable=False),
    sa.Column('max_weekly_hours', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_is_active'), 'employees', ['is_active'], unique=False)
    op.create_index(op.f('ix_employees_status'), 'employees', ['status'], unique=False)
    op.create_table('employee_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('proficiency_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'skill_name')
    )
    op.create_index(op.f('ix_employee_skills_category'), 'employee_skills', ['category'], unique=False)
    op.create_index(op.f('ix_employee_skills_employee_id'), 'employee_skills', ['employee_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_end_date'), 'projects', ['end_date'], unique=False)
    op.create_index(op.f('ix_projects_manager_id'), 'projects', ['manager_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('timesheets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'week_start')
    )
    op.create_index(op.f('ix_timesheets_employee_id'), 'timesheets', ['employee_id'], unique=False)
    op.create_index(op.f('ix_timesheets_status'), 'timesheets', ['status'], unique=False)
    op.create_index(op.f('ix_timesheets_week_start'), 'timesheets', ['week_start'], unique=False)
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('utilisation_percent', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_date < to_date', name='ck_allocations_dates'),
    sa.CheckConstraint('utilisation_percent >= 1 AND utilisation_percent <= 100', name='ck_allocations_utilisation'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_employee_id'), 'allocations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_allocations_project_id'), 'allocations', ['project_id'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_due_date'), 'milestones', ['due_date'], unique=False)
    op.create_index(op.f('ix_milestones_project_id'), 'milestones', ['project_id'], unique=False)
    op.create_index(op.f('ix_milestones_status'), 'milestones', ['status'], unique=False)
    op.create_table('project_health',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('health_status', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_health_health_status'), 'project_health', ['health_status'], unique=False)
    op.create_index(op.f('ix_project_health_project_id'), 'project_health', ['project_id'], unique=True)
    op.create_table('timesheet_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timesheet_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hours >= 0', name='ck_timesheet_entries_hours'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timesheet_id', 'project_id')
    )
    op.create_index(op.f('ix_timesheet_entries_project_id'), 'timesheet_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_timesheet_entries_timesheet_id'), 'timesheet_entries', ['timesheet_id'], unique=False)
    op.create_table('project_risk_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_health_id', sa.Integer(), nullable=False),
    sa.Column('flag_text', sa.Text(), nullable=False),
    sa.Column('is_positive', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_health_id'], ['project_health.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_risk_flags_project_health_id'), 'project_risk_flags', ['project_health_id'], unique=False)
    op.create_table('timesheet_entry_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timesheet_entry_id', sa.Integer(), nullable=False),
    sa.Column('activity_tag_id', sa.Integer(), nullable=False),
    sa.Column('custom_label', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['activity_tag_id'], ['activity_tags.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['timesheet_entry_id'], ['timesheet_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timesheet_entry_id', 'activity_tag_id')
    )
    op.create_index(op.f('ix_timesheet_entry_tags_timesheet_entry_id'), 'timesheet_entry_tags', ['timesheet_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timesheet_entry_tags_timesheet_entry_id'), table_name='timesheet_entry_tags')
    op.drop_table('timesheet_entry_tags')
    op.drop_index(op.f('ix_project_risk_flags_project_health_id'), table_name='project_risk_flags')
    op.drop_table('project_risk_flags')
    op.drop_index(op.f('ix_timesheet_entries_timesheet_id'), table_name='timesheet_entries')
    op.drop_index(op.f('ix_timesheet_entries_project_id'), table_name='timesheet_entries')
    op.drop_table('timesheet_entries')
    op.drop_index(op.f('ix_project_health_project_id'), table_name='project_health')
    op.drop_index(op.f('ix_project_health_health_status'), table_name='project_health')
    op.drop_table('project_health')
    op.drop_index(op.f('ix_milestones_status'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_project_id'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_due_date'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_allocations_project_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_employee_id'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_timesheets_week_start'), table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_status'), table_name='timesheets')
    op.drop_index(op.f('ix_timesheets_employee_id'), table_name='timesheets')
    op.drop_table('timesheets')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_manager_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_end_date'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_employee_skills_employee_id'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_category'), table_name='employee_skills')
    op.drop_table('employee_skills')
    op.drop_index(op.f('ix_employees_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_is_active'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_config')
    op.drop_table('activity_tags')
    # ### end Alembic commands ###
